name: kribb
description: "Real Estate App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get:
  font_awesome_flutter:
  path:
  intl:
  shared_preferences:
  lottie:
  url_launcher: ^6.1.12
  permission_handler: ^10.3.0
  intl_phone_field: ^3.2.0
  image_picker: ^1.0.1
  google_fonts:
  loading_animation_widget:
  group_radio_button:
  http:
  delightful_toast:
  flutter_carousel_widget:
  cached_network_image:
  readmore:
  rating_summary:
  shimmer: ^3.0.0-nullsafety.0
  path_provider:
  awesome_notifications:
  smooth_page_indicator:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter_native_splash:
  image: assets/images/dark_app_logo.png
  color: "#f9f9f9"
  image_dark: assets/images/light_app_logo.png
  color_dark: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Sk-Modernist
      fonts:
        - asset: fonts/Sk-Modernist/Sk-Modernist-Bold.otf
        - asset: fonts/Sk-Modernist/Sk-Modernist-Mono.otf
        - asset: fonts/Sk-Modernist/Sk-Modernist-Regular.otf
          weight: 700

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
